# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'InnovaEventManagement' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for InnovaEventManagement
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Crashlytics'
  pod 'GoogleSignIn'
  pod 'AppAuth'
end
